version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | bash
      - apt-get install -y nodejs
      - apt-get install -y build-essential
      - npm install -g serverless

  build:
    commands:
      - echo Build started on `date`
      - mvn test

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - serverless deploy --stage ${STAGE}

artifacts:
  type: zip
  files:
    – serverless.yml
    – target/transactions-api-dev.jar