version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | bash
      - apt-get install -y nodejs
      – apt-get -y update
      – npm install -g serverless@1.9.0

  build:
    commands:
      – mvn clean test

  post_build:
    commands:
      - mvn clean package

artifacts:
  type: zip
  files:
    – serverless.yml
    – target/transactions-api-dev.jar

discard-paths: yes