version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      -  mvn verify -DargLine="-Dstage=${STAGE}" -P integration-test

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: zip
  files:
    - buildspec-build.yml
    - buildspec-deploy.yml
    - buildspec-integration-test.yml
    - serverless.yml
    - target/transactions-api-dev.jar