version: 0.2

phases:
  build:
    commands:
      – mvn test

  post_build:
    commands:
      - mvn package

artifacts:
  type: zip
  files:
    – serverless.yml
    – target/transactions-api-dev.jar