version: 0.2

phases:
  build:
    commands:
      – mvn clean test

  post_build:
    commands:
      - mvn clean package

artifacts:
  type: zip
  files:
    – serverless.yml
    – target/transactions-api-dev.jar

discard-paths: yes