version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  type: zip
  files:
    - buildspec-build.yml
    - buildspec-deploy.yml
    - buildspec-integration-test.yml
    - pom.xml
    - serverless.yml
    - target/transactions-api-dev.jar