version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | bash
      - apt-get install -y nodejs
      - apt-get install -y build-essential
      - npm install -g serverless

  post_build:
    commands:
      - serverless deploy --stage ${STAGE}

artifacts:
  type: zip
  files:
    - buildspec-build.yml
    - buildspec-deploy.yml
    - buildspec-integration-test.yml
    - pom.xml
    - serverless.yml
    - target/transactions-api-dev.jar