service: aws-java-maven # NOTE: update this with your service name



provider:
  name: aws
  runtime: java8
  profile: devProfile
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    stage: ${opt:stage}

custom:
  alpha_wcu: 1
  alpha_rcu: 1
  beta_wcu: 5
  beta_rcu: 5

package:
  artifact: target/transactions-api-dev.jar

functions:
  get-transactions:
    handler: com.serverless.GetTransactionsHandler
    events:
      - http:
          path: /accounts/{account_id}/transactions
          method: get
  post-transaction:
    handler: com.serverless.PostTransactionsHandler
    events:
      - http:
          path: /accounts/{account_id}/transactions
          method: post

resources:
  Resources:
    transactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${opt:stage}_transactions_table
        AttributeDefinitions:
          - AttributeName: account_id
            AttributeType: S
          - AttributeName: transaction_date
            AttributeType: S
        KeySchema:
          - AttributeName: account_id
            KeyType: HASH
          - AttributeName: transaction_date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.${opt:stage}_rcu}
          WriteCapacityUnits: ${self:custom.${opt:stage}_wcu}